name: Build
on: [ push ]
concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 24

      - name: Cache Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/*
          key: ${{ runner.OS }}-maven-${{ hashFiles('**/pom.xml') }}

      - name: Set up Docker
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: Docker version
        run: docker version

      # Pull the images used by integration tests
      - name: Pull docker:dind
        run: docker pull docker:dind

      - name: Pull ghcr.io/hlesey/busybox
        run: docker pull ghcr.io/hlesey/busybox

      # Maven command-line options:
      # --batch-mode: recommended in CI to inform maven to not run in interactive mode (less logs)
      # -V: strongly recommended in CI, will display the JDK and Maven versions in use.
      # -Dsurefire.useFile=false: useful in CI. Displays test errors in the logs directly (instead of
      #                           having to crawl the workspace files to see the cause).
      # -e: Display stack-traces on failure
      - name: Build
        run: ./mvnw verify --batch-mode -V "-Dsurefire.useFile=false" -e